security:

    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            provider: user_provider
            oidc:
                check_path: /login
                user_identifier_property: sub
            entry_point: form_login
            form_login:
                login_path: login
                check_path: login
                enable_csrf: false # TODO: Enable CSRF protection
            logout:
                path: logout

    access_control:
        - { path: ^/login$, role: PUBLIC_ACCESS }
        - { path: ^/login_oidc$, role: PUBLIC_ACCESS }
        - { path: ^/, role: ROLE_USER }

    providers:
        user_provider:
            id: PowerADM\Security\UserProvider

    role_hierarchy:
        ROLE_EDITOR:      ROLE_USER
        ROLE_ADMIN:       ROLE_EDITOR
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10