parameters:
  forward_record_types: '%env(FORWARD_RECORD_TYPES)%'
  reverse_record_types: '%env(REVERSE_RECORD_TYPES)%'
  oidc_admin_role: '%env(OIDC_ADMIN_ROLE)%'
  oidc_editor_role: '%env(OIDC_EDITOR_ROLE)%'
  oidc_user_role: '%env(OIDC_USER_ROLE)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    PowerADM\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    PowerADM\Command\SetupCommand:
        autowire: false
        arguments:
            - '%kernel.secret%'
    PowerADM\EventListener\InsecureInstallationListener:
        autowire: false
        arguments:
            - '%kernel.secret%'